### ISSUE TITLE
Play Station 5

### ISSUE THREAD

**Issue by Jolge100** [andshrew/PS4-Updates-Python#1]
Is something like this possible for PS5 games as well?
thanks

**Comment by andshrew** [comment]
The current update for a PS5 game lives at a URL like:  
https://sgst.prod.dl.playstation.net/sgst/prod/00/np/PPSA01288_00/1db8a953-699b-47e8-8082-799b1eea8118-version.xml

As far as I know, there isn't a publicly known method for pre-determining what URL each individual PS5 game uses. So for now it isn't possible to do this for PS5 games.

**Comment by Jolge100** [comment]
I asked this because some websites like https://prosperopatches.com/ are doing something like this.
thanks

**Comment by andshrew** [comment]
As far as I know, that web site is pulling the patch information via a manually curated list of "version.xml" URLs. Someone had to either own the game on disc and extract the URL from one of the files, or they need a PSN connected PS4 of which they can externally decrypt the hard disk drive, from which you can then read a database file which apparently contains these URLs for the games that your account owns.

They have their own API you could query if you just want patch information: https://prosperopatches.com/api/lookup?titleid=PPSA01288

**Comment by Jolge100** [comment]
The API link you provided is really helpful, and I appreciate it. Do you have an API link from the same website that would allow me to find the links to the pkg files, which are directly hosted on Sony’s servers? I could get them from the site itself, but the website is both behind Cloudflare and uses reCAPTCHA 2.

**Comment by andshrew** [comment]
No, I don't have anything more than that.
